#!perl
use strict;
use warnings;
use WWW::Facebook::API;

my $cb     = 'http://www.unobe.com/perl-wfa/test.cgi';
my $client = WWW::Facebook::API->new(
    callback       => $cb,
    desktop        => 0,
    format         => 'JSON',
    throw_errors   => 1,
    parse_response => 0,        # uses JSON::XS if set to 1
);

print "Enter your public API key: ";
chomp( my $val = <STDIN> );
$client->api_key($val);
print "Enter your API secret: ";
chomp($val = <STDIN> );
$client->secret($val);

print "Enter your e-mail address: ";
chomp(my $email = <STDIN> );
$client->secret($val);
print "Enter your password: ";
chomp(my $pass = <STDIN> );

my $token = $client->auth->login( email => $email,  pass => $pass );
$client->auth->get_session( $token );

use Data::Dumper;
my $friends_perl = $client->friends->get;
print Dumper $friends_perl;

my $notifications_perl = $client->notifications->get;
print Dumper $notifications_perl;

# Current user's quotes
my $quotes_perl = $client->users->get_info(
    uids   => $friends_perl,
    fields => ['quotes']
);
print Dumper $quotes_perl;

$client->auth->logout;
