#!perl
use strict;
use warnings;
use WWW::Facebook::API;

my $client = WWW::Facebook::API->new(
    desktop        => 1,
    throw_errors   => 1,
    parse          => 0,
    format         => 'XML',
);

print "Enter your public API key: ";
chomp( my $val = <STDIN> );
$client->api_key($val);
print "Enter your API secret: ";
chomp($val = <STDIN> );
$client->secret($val);

print "Enter your e-mail address: ";
chomp(my $email = <STDIN> );
$client->secret($val);
print "Enter your password: ";
chomp(my $pass = <STDIN> );

my $token = $client->auth->login( email => $email,  pass => $pass );
$client->auth->get_session( $token );

use Data::Dumper;
my $friends_xml = $client->friends->get;
print Dumper $friends_xml;

my $notifications_xml = $client->notifications->get;
print Dumper $notifications_xml;

# Current user's quotes
my $quotes_xml = $client->users->get_info(
    uids   => [ $client->session_uid ],
    fields => ['quotes']
);
print Dumper $quotes_xml;

$client->auth->logout;
